lesson_3/food/app_food/urls.py
from django.urls import path
from .views import main, catalog, category

urlpatterns = [
    path('catalog/', catalog, name='catalog'),
    path('', main, name='main'),
    path('catalog/category/<int:pk>/', category, name='category')
]

lesson_3/food/app_meal/urls.py
from django.urls import path
from .views import menu


urlpatterns = [
    path('menu/', menu, name='menu')
]

lesson_3/food/blog/urls.py
from django.urls import path
from .views import NewsListView, RegisterNews, NewsDetailView

urlpatterns = [
    path('news-list/', NewsListView.as_view(), name='news-list'),
    path('new_news/', RegisterNews.as_view(), name='register-news'),
    path('news-list/<int:pk>/', NewsDetailView.as_view(), name='news-detail')
]

lesson_3/food/food/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_food.urls')),
    path('restauraunt/', include('app_meal.urls')),
    path('blog/', include('blog.urls'))

]

lesson_3/food/app_food/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='название категории')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    name = models.CharField(max_length=20, verbose_name='название продукта')
    price = models.FloatField(verbose_name='цена')
    description = models.TextField(verbose_name='описание')
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 verbose_name='категория')

    class Meta:
        db_table = 'products'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'{self.name}'

lesson_3/food/app_meal/models.py
from django.db import models

class Ingredient(models.Model):

    name = models.CharField(max_length=20, unique=True, verbose_name='название ингредиента')
    ingredient_amount = models.FloatField(verbose_name='грамм')

    class Meta:

        db_table = 'ingredient'
        verbose_name = 'ингредиент'
        verbose_name_plural = 'ингредиенты'

    def __str__(self):
        return f'{self.name}'



class Meal(models.Model):

    name = models.CharField(max_length=20, unique=True, verbose_name='название блюда')
    price = models.FloatField(verbose_name='цена блюда')
    ingredient = models.ManyToManyField(Ingredient, verbose_name='ингредиенты',
                                        related_name='meals')

    class Meta:

        db_table = 'meal'
        verbose_name = 'блюдо'
        verbose_name_plural = 'блюда'

    def __str__(self):
        return f'{self.name}'

lesson_3/food/blog/models.py
from django.db import models


class Author(models.Model):
    username = models.CharField(max_length=20, verbose_name='Логин')
    first_name = models.CharField(max_length=20, verbose_name='Имя')
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='email', max_length=50)

    class Meta:
        db_table = 'authors'

    def __str__(self):
        return f'{self.username}'


class News(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок',
                             db_index=True)
    content = models.TextField(verbose_name='Содержание', default='')
    published_at = models.DateTimeField(auto_now_add=True,
                                        verbose_name='Дата публикации')
    updated_at = models.DateTimeField(auto_now=True)
    status_choices = [
        ('a', 'Active'),
        ('i', 'Inactive')
    ]
    activity_flag = models.CharField(max_length=1, choices=status_choices,
                                     default='i')
    author = models.ForeignKey(Author, verbose_name='автор', on_delete=models.CASCADE)

    class Meta:
        db_table = 'news'
        ordering = ['-published_at']
        permissions = [
            ('can_publish', 'Может опубликовать новость')
        ]

    def __str__(self):
        return f'{self.title}'


class Comment(models.Model):

    email = models.EmailField(max_length=50, verbose_name='email')
    username = models.CharField(max_length=20, verbose_name='логин')
    comment = models.TextField(verbose_name='комментарий')
    published_at = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')
    news = models.ForeignKey(News, on_delete=models.CASCADE, verbose_name='новость')

    class Meta:
        db_table = 'comments'
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

    def __str__(self):
        return f'{self.email}'

lesson_3/food/blog/forms.py
from django import forms
from .models import News, Comment


class PostForm(forms.Form):
    title = forms.CharField(max_length=50, label='Заголовок новости: ')
    content = forms.CharField(widget=forms.Textarea, label='Содержание')
    username = forms.CharField(max_length=20, label='Логин')
    last_name = forms.CharField(max_length=20, label='Фамилия')
    first_name = forms.CharField(max_length=20, label='Имя')
    email = forms.EmailField(max_length=50, label='email')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['news', 'published_at']

lesson_3/food/app_food/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Product, Category


def main(request, *args, **kwargs):
    return render(request, 'app_food/base.html')


def catalog(request, *args, **kwargs):
    categories = Category.objects.all()
    return render(request, 'app_food/index.html', context={'categories': categories})


def category(request, *args, **kwargs):
    products = Product.objects.filter(category__id=kwargs['pk'])
    return render(request, 'app_food/category.html', context={
        'products': products
    })

lesson_3/food/app_meal/views.py
from django.shortcuts import render
from .models import Meal, Ingredient


def menu(request, *args, **kwargs):
    if request.method == 'GET':
        meals = Meal.objects.prefetch_related('ingredient').all()
        # ingredients = Ingredient.objects.all()
        return render(request, 'app_meal/index.html', context={'meals': meals})
                                                               #'ingredients': ingredients})

lesson_3/food/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, View, DetailView
from .models import News, Author, Comment
from .forms import PostForm, CommentForm


class NewsListView(ListView):
    model = News
    template_name = 'blog/news-list.html'
    context_object_name = 'news'
    queryset = News.objects.filter(
        activity_flag='a'
    )


class NewsDetailView(DetailView):

    def get(self, request, *args, **kwargs):
        news_id = self.kwargs['pk']
        news = get_object_or_404(News, pk=news_id)

        comment_form = CommentForm()


        return render(request, 'blog/news_detail.html',
                      context={'news': news, 'comment_form': comment_form})

    def post(self, request, *args, **kwargs):
        news_id = self.kwargs['pk']
        news = get_object_or_404(News, pk=news_id)

        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = Comment(news=news, **comment_form.cleaned_data)
            comment.save()

        return redirect('news-detail', pk=news_id)


class RegisterNews(View):

    def get(self, request):
        news_form = PostForm()
        return render(request, 'blog/news_form.html',
                      context={'news_form': news_form})

    def post(self, request):
        news_form = PostForm(request.POST)
        if news_form.is_valid():
            data = news_form.cleaned_data

            new_author = Author.objects.create(
                username=data['username'],
                last_name=data['last_name'],
                first_name=data['first_name'],
                email=data['email']
            )
            new_author.save()

            new_news = News.objects.create(title=data['title'],
                                           content=data['content'],
                                           activity_flag='i',
                                           author=new_author)
            new_news.save()

        return redirect('news-list')

lesson_3/food/app_food/templates/app_food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
</head>
<body>
<header>
    <h1>Shop app</h1>
    <a href="{% url 'main' %}">Главная страница</a>
    <a href="{% url 'catalog' %}">Каталог</a>
</header>
{% block products %}

{% endblock %}

</body>
</html>

lesson_3/food/app_food/templates/app_food/category.html
{% extends 'app_food/base.html' %}

{% block products %}

<ul>
    {% for product in products %}

        <li>
            <h3>{{product.name}}</h3>
            <p>{{product.description}}</p>
            <button>{{product.price}}</button>
        </li>
    {% endfor %}
</ul>

{% endblock %}

lesson_3/food/app_food/templates/app_food/index.html
{% extends 'app_food/base.html' %}

{% block products %}

<div>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'category' category.id %}" >{{category.name}}</a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

lesson_3/food/app_meal/templates/app_meal/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ресторан</title>
</head>
<body>
    <h1>Блюда</h1>
    <ul>
        {% for meal in meals %}
            <li>
                <h2>{{meal.name}}</h2>
                <p>Ингредиенты: </p>
                <ul>
                    {% for ingredient in meal.ingredient.all %}
                    <li>
                        <p>{{ingredient.name}}</p>
                    </li>
                {% endfor %}
                </ul>
                <p>{{meal.price}} руб.</p>
            </li>
        {% empty %}
        <h3>Блюд пока нет</h3>
        {% endfor %}
    </ul>
    <ul>
        {% for ingredient in ingredients %}
            <li>
                <p>Этот ингредиент <b>{{ingredient.name}}</b> встречается в блюдах:</p>
                <ul>
                    {% for meal in ingredient.meals.all %}
                        <p>{{meal.name}}</p>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

lesson_3/food/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<main>
    <header>
        <h1>Блог новостей</h1>
        <div class="links">
            <a href="{% url 'news-list' %}">Новости</a>
            <a href="{% url 'register-news' %}">Расскажи новость</a>
        </div>
    </header>
    <div class="container">
        {% block news_list %}
        {% endblock %}
        {% block news_form %}
        {% endblock %}
    </div>
</main>
</body>
</html>

lesson_3/food/blog/templates/blog/news-list.html
{% extends 'blog/base.html' %}

{% block news_list %}

    {% for i_news in news %}
    <a href="{% url 'news-detail' i_news.id %}">
        <div class="news">
            <h2>{{i_news.title}}</h2>
            <span>Опубликовано: {{i_news.published_at|date:"SHORT_DATE_FORMAT"}} {{i_news.published_at|time:"H:i"}}</span>
            <br>
            <span>Изменено: {{i_news.updated_at|date:"SHORT_DATE_FORMAT"}} {{i_news.updated_at|time:"H:i"}}</span>
            <p>{{i_news.content|truncatewords:20}}</p>
        </div>
    </a>
    {% empty %}
    <h3>Новостей пока нет...</h3>
    {% endfor %}
{% endblock %}

lesson_3/food/blog/templates/blog/news_detail.html
{% extends 'blog/base.html' %}

{% block news_list %}

<div class="news">
    <h2>{{news.title}}</h2>
    <span>{{news.author.username}} {{news.published_date}}</span>
    <h3>Автор: {{news.author.first_name}} {{news.author.last_name}}</h3>
    <p>{{news.content}}</p>

    <h4>Оставьте обратную связь автору:
        <a href="mailto:{{news.author.email}}">{{news.author.email}}
        </a>
    </h4>
    <div class="comments">

        <h2>Комментарии</h2>
        <ul>
            {% for comment in news.comment_set.all %}
                <li>
                    <h4>От: {{ comment.email }}</h4>
                    <p>Опубликовано: {{ comment.published_at }}</p>
                    <p>{{ comment.comment }}</p>
                </li>
            {% empty %}
                <li>Комментариев пока нет.</li>
            {% endfor %}
        </ul>
         <h3>Оставьте комментарий: </h3>
        <form method="post">
            {% csrf_token %}
            {{comment_form.as_p}}
            <button type="submit">Отправить</button>
        </form>
    </div>
</div>

{% endblock %}

lesson_3/food/blog/templates/blog/news_form.html
{% extends 'blog/base.html' %}

{% block news_form %}
    <form method="post">
        {% csrf_token %}
        {{news_form.as_p}}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}